/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.duplicatecopyofonline_reservation_stystem;


import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SURAJ
 */
public class DislpayRecords extends javax.swing.JFrame {

          Connection conn = null;
          PreparedStatement st = null;
          ResultSet rst = null;
    public DislpayRecords() {
        initComponents();
        Toolkit toolkit =getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
        table.setVisible(false);
        conn = JConnector.Connect();
        
    }

    private void UpdateTable(){
        DefaultTableModel model = (DefaultTableModel)table.getModel();
        try{
            
            Statement stmt = conn.createStatement();
            String sql = "select * from reservation where PNR ='"+pnrfield.getText()+"'";
            rst = stmt.executeQuery(sql);
           while(rst.next()){
              int srno = rst.getInt("SRNO");
               String name = rst.getString("NAME");
               String age = rst.getString("AGE");
               String sex = rst.getString("SEX");
               String tno = rst.getString("TRAINNUMBER");
               String tname = rst.getString("TRAINNAME");
               String ctype = rst.getString("CLASSTYPE");
               String fstate = rst.getString("FROMSTATE");
               String tstate = rst.getString("TOSTATE");
               String fcapital = rst.getString("FROMCAPITAL");
               String tcapital = rst.getString("TOCAPITAL");
               String fcity = rst.getString("FROMCITY");
               String tcity = rst.getString("TOCITY");
               String date = rst.getString("DATES");
               String nopsng = rst.getString("NOOFPSSNGRS");
               String adult = rst.getString("ADULT");
               String child = rst.getString("CHILD");
               String pnr = rst.getString("PNR");
               
               model.addRow(new Object[]{srno,name,age,sex,tno,tname,ctype,fstate,tstate,fcapital,tcapital,fcity,tcity,date,nopsng,adult,child,pnr});
           }
        }catch(Exception e){
            System.out.println("Something went wrong");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnrfield = new javax.swing.JTextField();
        ok = new javax.swing.JButton();
        back = new javax.swing.JButton();
        back1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SR.NO", "NAME", "AGE", "SEX", "TRAINNUMBER", "TRAINNAME", "CLASSTYPE", "FROMSTATE", "TOSTATE", "FROMCAPITAL", "TOCAPITAL", "FROMCITY", "TOCITY", "DATE", "NO.OF.PSNGRS", "ADULT", "CHILD", "PNR"
            }
        ));
        jScrollPane2.setViewportView(table);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 1870, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 2120, 20));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("             Reservation Cancellation Panel                               ");
        jLabel1.setFocusable(false);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("Enter PNR : ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        pnrfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pnrfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pnrfieldFocusLost(evt);
            }
        });
        pnrfield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnrfieldMouseExited(evt);
            }
        });
        pnrfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pnrfieldKeyTyped(evt);
            }
        });
        getContentPane().add(pnrfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 220, 30));

        ok.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ok.setText("Delete ");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        getContentPane().add(ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, -1, -1));

        back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        back.setText("Display");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, -1, -1));

        back1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        back1.setText("Back");
        back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back1ActionPerformed(evt);
            }
        });
        getContentPane().add(back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
            
        try{
                String del = "delete from reservation where PNR='"+pnrfield.getText()+"'";
                PreparedStatement ps = conn.prepareStatement(del);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Records Deleted Successfully!");
                new login().setVisible(true);
                dispose();
            }catch(SQLException | HeadlessException ex){
                System.out.println("Failed");
                JOptionPane.showMessageDialog(null,ex);           
            }
    }//GEN-LAST:event_okActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        table.setVisible(true);
        UpdateTable();
    }//GEN-LAST:event_backActionPerformed

    private void pnrfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pnrfieldFocusLost
           
    }//GEN-LAST:event_pnrfieldFocusLost

    private void pnrfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pnrfieldKeyTyped
    
    }//GEN-LAST:event_pnrfieldKeyTyped

    private void pnrfieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnrfieldMouseExited
        
    }//GEN-LAST:event_pnrfieldMouseExited

    private void pnrfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pnrfieldFocusGained
        
    }//GEN-LAST:event_pnrfieldFocusGained

    private void back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_back1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DislpayRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DislpayRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DislpayRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DislpayRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DislpayRecords().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton back1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton ok;
    private javax.swing.JTextField pnrfield;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
