/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Swing_Framework_Application;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author suraj
 */
public class AddNewQuestion extends javax.swing.JFrame {

    /**
     * Creates new form AddNewQuestion
     */
    public AddNewQuestion() {
        initComponents();
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/swing","root","root");
            Statement st = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ResultSet rs = st.executeQuery("select count(ID) from question");
            
            if(rs.first()){
                int ID = rs.getInt(1);
                ID = ID+1;
                
                String str = String.valueOf(ID);
                QueId.setText(str);
            }
            else{
                QueId.setText("1");
            }
            
        }
        catch(Exception e){
            JFrame jf = new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Exit = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        Answer = new javax.swing.JTextField();
        Question = new javax.swing.JTextField();
        Opt1 = new javax.swing.JTextField();
        Opt2 = new javax.swing.JTextField();
        Opt3 = new javax.swing.JTextField();
        Opt4 = new javax.swing.JTextField();
        jToggleButton3 = new javax.swing.JToggleButton();
        QueId = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Only Admin Can Edit This Field");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 724, 80));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOpaque(true);
        kGradientPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 101, 745, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Option 1:");
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 90, 35));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("Question ID:");
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 150, 32));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Option3:");
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 90, 35));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Question");
        kGradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 118, 35));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("Option 2:");
        kGradientPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 90, 35));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("Answer:");
        kGradientPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 520, 118, 35));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setText("Option4:");
        kGradientPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 90, 35));

        Exit.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        kGradientPanel1.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 590, 170, 60));

        jToggleButton2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jToggleButton2.setText("Submit");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 590, 170, 60));

        Answer.setBackground(new java.awt.Color(0, 0, 0,1));
        Answer.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        Answer.setForeground(new java.awt.Color(255, 255, 255));
        Answer.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 255, 204)));
        kGradientPanel1.add(Answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 520, 990, 40));

        Question.setBackground(new java.awt.Color(0, 0, 0,1));
        Question.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        Question.setForeground(new java.awt.Color(255, 255, 255));
        Question.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 255, 204)));
        kGradientPanel1.add(Question, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 990, 40));

        Opt1.setBackground(new java.awt.Color(0, 0, 0,1));
        Opt1.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        Opt1.setForeground(new java.awt.Color(255, 255, 255));
        Opt1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 255, 204)));
        kGradientPanel1.add(Opt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 990, 40));

        Opt2.setBackground(new java.awt.Color(0, 0, 0,1));
        Opt2.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        Opt2.setForeground(new java.awt.Color(255, 255, 255));
        Opt2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 255, 204)));
        kGradientPanel1.add(Opt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 990, 40));

        Opt3.setBackground(new java.awt.Color(0, 0, 0,1));
        Opt3.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        Opt3.setForeground(new java.awt.Color(255, 255, 255));
        Opt3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 255, 204)));
        kGradientPanel1.add(Opt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 990, 40));

        Opt4.setBackground(new java.awt.Color(0, 0, 0,1));
        Opt4.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        Opt4.setForeground(new java.awt.Color(255, 255, 255));
        Opt4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 255, 204)));
        kGradientPanel1.add(Opt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 990, 40));

        jToggleButton3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jToggleButton3.setText("Clear");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jToggleButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 590, 170, 60));

        QueId.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        QueId.setForeground(new java.awt.Color(255, 255, 255));
        QueId.setText("00");
        kGradientPanel1.add(QueId, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, 30));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        new AdminHome().setVisible(true);
       dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        String id=QueId.getText();
        String question = Question.getText();
        String opt1 = Opt1.getText();
        String opt2 = Opt2.getText();
        String opt3 = Opt3.getText();
        String opt4 = Opt4.getText();
        String answer = Answer.getText();
        try{
             //Opening Connection...
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/swing","root","root");
                
                 String q="insert into question(ID,Question,Opt1,Opt2,Opt3,Opt4,Answer) values (?,?,?,?,?,?,?)";
            PreparedStatement ps = con.prepareStatement(q);
            
            
           ps.setString(1,id);
            ps.setString(2,question);
            ps.setString(3,opt1);
            ps.setString(4,opt2);
            ps.setString(5,opt3);
            ps.setString(6,opt4);
            ps.setString(7,answer);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Succefully Inserted!");
            dispose();
            new AddNewQuestion().setVisible(true);
        }
        catch(HeadlessException | SecurityException | SQLException e){
            JOptionPane.showMessageDialog(this,"Something Went Wrong","Warning",JOptionPane.WARNING_MESSAGE);
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddNewQuestion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // TODO add your handling code here:
        Answer.setText("");
        Question.setText("");
        Opt1.setText("");
        Opt2.setText("");
        Opt3.setText("");
        Opt4.setText("");
        
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewQuestion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Answer;
    private javax.swing.JToggleButton Exit;
    private javax.swing.JTextField Opt1;
    private javax.swing.JTextField Opt2;
    private javax.swing.JTextField Opt3;
    private javax.swing.JTextField Opt4;
    private javax.swing.JLabel QueId;
    private javax.swing.JTextField Question;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
